[amazon]
10.0.3.173 ansible_user=ec2-user
10.0.4.63  ansible_user=ec2-user
10.0.3.159 ansible_user=ec2-user

[ubuntu]
10.0.3.239 ansible_user=ubuntu
10.0.4.220 ansible_user=ubuntu
10.0.3.180 ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
